### ISSUE TITLE
Unhandled "Channel ended" rejection in tests

### ISSUE THREAD

**Issue by eddieajau** [mateodelnorte/sourced#15]
Hi Matt.

This may not be you, but I'm trying to work out where the following error is coming from in my test suite:

```
Potentially unhandled rejection [6] Error: Channel ended, no reply will be forthcoming
```

When I'm testing one file using the Service Bus as a dependency, I don't see the problem, for example the code is:

```typescript
export function registerWorkflow(serviceBus: Bus, wampClient: WampClient) {
	serviceBus.listen('on.file.created', { ack: true }, (event: any) => {
		event.handle.ack();
		serviceBus.send('do.file.validate', event);
	});

	serviceBus.listen('on.file.validated', { ack: true }, (event: any) => {
		event.handle.ack();
		serviceBus.send('do.file.transform', event);
	});

	serviceBus.listen('on.file.transformed', { ack: true }, (event: any) => {
		// TODO ack should really occur after message published?
		event.handle.ack();
		wampClient.publish('on.file.ready.' + event.createdBy, [event.name], {}, {
			exclude_me: false,
			acknowledge: true
		});
	});
}
```

But when I run the full test suite, I get that unhandled rejection.

Before each test I do:

```typescript
export function createServiceBus(config: Config): Bus {
	let serviceBus: Bus = bus(config.get('amqp'));

	serviceBus.use(retry({
		store: retry.MemoryStore()
	}));

	return serviceBus;
}
```

and then after each test I do:

```typescript
export function closeServiceBus(serviceBus: Bus): Promise<void> {
	return new Promise<void>((resolve) => {
		setTimeout(() => {
			serviceBus.close();
			resolve();
		}, 10)

	});
}
```

I added the timeout because the Service Bus still seems to be doing things after my test is finished.

I'm guessing I'm closing the connection and there is a listener still working. Assuming I've given you enough information, is there any way to close down my tests more elegantly?

Thanks in advance.

**Comment by mateodelnorte** [comment]
This would be an issue for https://github.com/mateodelnorte/servicebus, though it might be one for amqplib. If you like, you can reopen it in /servicebus. 

That said, I haven't done much work to make sure that bus instances can be instantiated after any have been closed. amqplib is pretty finicky when a channel is closed, and inherits a lot of really weird behavior from the AMQP protocol and RabbitMQ itself. From an app-development perspective - typically, if you're closing your bus it's because you're application is closing after error or because you're shutting it down. 

In test suites, I've always seen test suites reusing a single instance. Not sure you get a big benefit from completely breaking down the connection and starting it back up again. 

Can you refactor your test suite to use the same instance without closing? Any reason you need to close after each test?

**Comment by eddieajau** [comment]
Found a workaround. I just increased the timeout in `closeServiceBus` to 50 ms and it goes away.

**Comment by mateodelnorte** [comment]
Interesting. I'll see if I can track down what's happening.
