### ISSUE TITLE
Question - Inter-process events

### ISSUE THREAD

**Issue by otaviosoares** [mateodelnorte/sourced#16]
Hello, I got to know this project through the amazing presentation given by Stefan Kutko about how they've build a solution with Event Sourcing using sourced.

I'm willing to use sourced too, but I have a question: As sourced uses EventEmitter to emit the queued events, what would be the best practice to propagate these events to other microservices? Just listen for the EventEmitter event and then re-emit it using pub/sub?

Thank you

**Comment by mateodelnorte** [comment]
Hi @otaviosoares. The answer to this question is to use https://github.com/mateodelnorte/servicebus. Servicebus allows interprocess communication via RabbitMQ. Because your processes use queues to send messages between one another, they'll be reliable and your processes can then be transactional and your system eventually consistent. 

For a more structured way to build services with servicebus, see https://github.com/mateodelnorte/servicebus-register-handlers.

**Comment by mateodelnorte** [comment]
For something more structured than that, check out https://github.com/mateodelnorte/microsvc but note it's pre-pre alpha.

**Comment by mateodelnorte** [comment]
And yes, in your handlers you'll want to listen for events from your entities and publish when they emit post-commit.

**Comment by otaviosoares** [comment]
Thanks @mateodelnorte . I closed the issue because I just found the answer in the presentation.

http://slides.com/stefankutko/nodejs-microservices-event-sourcing-cqrs#/36

Thank you anyway.
