### ISSUE TITLE
replay / emit

### ISSUE THREAD

**Issue by AlexZeitler** [mateodelnorte/sourced#17]
As replay doesn't emit by default, how can I replay including emit so I can update the read model?

The scenarios I'm trying to grasp are as follows: 

1. My subscriber v1 which created the read model from an event has a bug. I fixed that bug but I need the events again to fix the read model.
2. I add a new subscriber to create another read model and I want to build the read model using existing events. How would you emit again without creating existing read models again (overwrite them)?

**Comment by mateodelnorte** [comment]
There are a few ways to go about this. 

1) Create an event your service can listen for whose sole purpose is to publish another event stating it's entity's current state. You'll need additional handlers in downstream services to overwrite locations that update that state, and they may not be the same handlers in use now. If the structure of this new event matches that of the old event, you may be able to get away with using the old downstream handlers. 
2) Code your individual services and the event-based operations they perform to be idempotent. This way, you can just fire the same message you fired in the first place, and it will arrive at the same state. 
3) Rest assured that you've fixed your bug, going forward. Write a manual migration to update the downstream data and go about your day. You can do this by manually instantiating your repository, pulling in the entity or entities you need, executing whatever methods you need, and publishing in reaction to the events. You can even load the event and manually call .emit() on it externally. You pick the rules you follow or break on any given day. Better to fix bugs than be too strict about the rules. ;)

All said, #2) is something you should aim to do as much as possible. This will help make these scenarios easier to deal with when they happen as most situations will be correctable by fixing the downstream bug and clicking a button and causing an action again.

**Comment by AlexZeitler** [comment]
@mateodelnorte Thanks for your fast reply. 2) what I absolutely try to do already :+1: 
I think your proposed solutions will work for me.

But I came up with another problem while thinking about replaying from the repository:
What if I reload the events from the repo and I've snapshots which contain wrong data due to previous bugs?

If I replay event by event having the bug fixed in the particular method, my entity state eventually is right. But what if snapshots are involved as described?

**Comment by mateodelnorte** [comment]
It should all be eventually consistent. 

If your snapshots are wrong and no events have occurred since, then the bug is not fixed. In this case, you need to write a migration to fix your bug. So, code fix + migration fix = whole fix. 

If your snapshots are wrong and some events have occurred, but perhaps have not affected the entity properties which need fixing - then you have the same situation as above. 

If your snapshots are wrong and some events have occurred, and have run against the new, fixed code then it's quite possible your problem is solved by the fact your code is idempotent. The properties now have the correct values (at least in the originating service). You just need to check downstream services for any ill effects. If you're just talking about a denormalizer which writes to a read model (always prefer upserts here!) then you should be fine. If the event caused a non-overwriteable action like an email - figure out what happened and make a migration or a human intervention (aka Sorry Email!). 

As a further note - snapshots are sometimes your get out of jail free card, as well. Not sure exactly what the state of things will be if your events are replayed on top of a snapshot? Screw it. Write a migration that sets your entity to the correct state, then commit to the repository with forceSnapshot. Boom. Next load comes straight from snapshot.

**Comment by AlexZeitler** [comment]
Ok, so I understood it correctly. Thanks for confirmation and your time to answer that fast.
And of course thanks for sourced and the stuff you build around it :+1:

**Comment by mateodelnorte** [comment]
Sure thing! If you've got time, I'd love to hear about your experience with sourced - what you think of it, what things you've liked, what you didn't, and what you've been building with it. That kind of feedback gives me great insight to where I should focus my efforts. Feel free to send to github (at) iammattwalters.com.

**Comment by AlexZeitler** [comment]
Thanks, will do that as we're currently starting to use it in at least 2 projects. One thing was documentation but as it looks like,  93871c8 fixed this as pretty much :+1:

**Comment by mateodelnorte** [comment]
Yup. That's totally been a problem! I've spent all my time building stuff with my open sourced tools over the past four years or so and not enough time making it easy for others to do so!

I'm currently taking some time off to fix that problem!
