### ISSUE TITLE
Best way to handle validation?

### ISSUE THREAD

**Issue by eddieajau** [mateodelnorte/sourced#20]
Hi Matt.

Just want to confirm the best way to handle validation. Would you do something like this:

``` typescript
export class Customer exends Entity {
  public create(props: any) {
    if (!props.id) {
      let err = new Error('Customer: <id> required.');
      this.emit('error', err);
      throw err;
    }
    // ... enqueue and emit success event
  }
}
```

Thanks in advance.

**Comment by mateodelnorte** [comment]
Personally, I don't think Errors should be thrown or emitted for validation. I think Errors should be reserved for things having gone to hell, and now you need to bounce your process. The reason is because I don't want to do special casing to determine if the error was an error, or not really an error and just validation. 

I'd personally prefer to `this.emit('invalidated', { reason });`. 

That said, it's a good practice to validate the params you're sending into your Entities _before_ you call your entity methods. And doing so as soon as possible is better. If you can validate in a web app before you send a command to a Customer-svc, that's best. If you can't validate there, but can validate in a handler before executing an entity method, that's better. If you can only validate inside the Entity, with the Entity's current data - that's ok, but may result in you having to listen for special validation events, reacting to them, publishing them back to the originating app or service and updating some info there. Validating earlier saves you from having to do all that, so it's good to spend some brain cycles determining if that's possible.

**Comment by eddieajau** [comment]
Yeah, I'm trying to decide where to draw the boundary and comparing _models_ to how, for example, Sequelize does things where you set your properties and then validation is done effectively at commit time. 

I guess validation does need to be decoupled from the event method in the entity because it could cause all manner of problems when events are replayed (imagining that you've changed from having on field as optional, and then it becomes required).

And you are right, I wouldn't throw an error for validation (but I could certainly emit them).
