### ISSUE TITLE
replaying

### ISSUE THREAD

**Issue by skbolton** [mateodelnorte/sourced#30]
I am confused by the need for `this.replaying`. Isn't the `entity.replay(events)` a synchronous call or am I missing something?

**Comment by mateodelnorte** [comment]
replay is called when you deserialize an entity from a data store, like in https://github.com/mateodelnorte/sourced-repo-mongo/blob/master/index.js#L253. if you are rehydrating an object from a data store from a snapshot and events, you don't want to emit a bunch of events that were already emitted because a method on that entity was called before it was persisted.
